Minor type annotation fix
AIStream-Peelout/flow-forecast pull request #575
Opened 2022-08-06 21:35 UTC by victorcwai

Update `save_path: str = None` to `save_path: str = ""`.

2022-08-10 14:51 UTC, isaacmg requested changes
That won't necessarily work since `if save_path` is used later in the code [on ln 56](https://github.com/AIStream-Peelout/flow-forecast/blob/27fb5d898f8f6dd44798cfaabe03e98704bd09ca/flood_forecast/da_rnn/train_da.py#L56) . If that were changed form None the other line would have to become `if len(save_path)>0` Also why are you removing the more descriptive Tuple?

2022-08-13 00:42 UTC, victorcwai commented
Hi. An empty string would evaluate to false, so we would not need to change `if save_path`.
The type checker we use (`pyre`) indicates a type mismatch as `save_path: str` is declared a `str` but assigned to `None`.

2022-08-26 08:24 UTC, luca-digrazia commented
Merge?

2022-08-30 21:41 UTC, isaacmg approved these changes

2022-08-30 21:41 UTC, merged